language: objective-c
before_install:
  - gem install cocoapods
  - gem install xcpretty
  - cd Tests && pod install && cd $TRAVIS_BUILD_DIR
script: "make test"
notifications:
  irc: "chat.freenode.net#cocode"

